//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhysioApplication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhysioApplication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Athletes Information.
        /// </summary>
        public static string StringAccessAthletesInformation {
            get {
                return ResourceManager.GetString("StringAccessAthletesInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All information pertaining to athletes including medical reports, diet, physical conditioning can be viewed here..
        /// </summary>
        public static string StringAccessAthletesInformationDescription {
            get {
                return ResourceManager.GetString("StringAccessAthletesInformationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Settings.
        /// </summary>
        public static string StringChangeSettings {
            get {
                return ResourceManager.GetString("StringChangeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new tests, physical exams etc. over here.
        /// </summary>
        public static string StringChangeSettingsDescription {
            get {
                return ResourceManager.GetString("StringChangeSettingsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View  Historical Trends.
        /// </summary>
        public static string StringViewHistoricalTrends {
            get {
                return ResourceManager.GetString("StringViewHistoricalTrends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphical reports showing historical information of athletes can be generated here..
        /// </summary>
        public static string StringViewHistoricalTrendsDescription {
            get {
                return ResourceManager.GetString("StringViewHistoricalTrendsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Notifications.
        /// </summary>
        public static string StringViewNotifications {
            get {
                return ResourceManager.GetString("StringViewNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items requiring your attention, notifications of upcoming activities etc. can be viewed here..
        /// </summary>
        public static string StringViewNotificationsDescription {
            get {
                return ResourceManager.GetString("StringViewNotificationsDescription", resourceCulture);
            }
        }
    }
}
